name: CI
on:
  push:
    branches: [main]
  pull_request:
permissions: {}
jobs:
  check:
    name: Check
    permissions:
      contents: read
    uses: openbunny/.github/.github/workflows/reusable-check.yml@2383033519e5dd89bfd4e832659933a145e7acde
