name: CI
on:
  push:
    branches: [main]
  pull_request:
permissions: {}
jobs:
  check:
    name: Check
    permissions:
      contents: read
    uses: openbunny/.github/.github/workflows/reusable-check.yml@0ef30bf859265abac45761ddb0907022555ab7c5
