name: DCO
on:
  pull_request:
permissions: {}
jobs:
  dco:
    name: DCO
    permissions:
      contents: read
    uses: openbunny/.github/.github/workflows/reusable-dco.yml@0ef30bf859265abac45761ddb0907022555ab7c5
