name: gitleaks
on:
  push:
    branches: [main]
  pull_request:
permissions: {}
jobs:
  gitleaks:
    name: gitleaks
    permissions:
      contents: read
    uses: openbunny/.github/.github/workflows/reusable-gitleaks.yml@0ef30bf859265abac45761ddb0907022555ab7c5
