name: reuse
on:
  push:
    branches: [main]
  pull_request:
permissions: {}
jobs:
  reuse:
    name: reuse
    permissions:
      contents: read
    uses: openbunny/.github/.github/workflows/reusable-reuse.yml@0ef30bf859265abac45761ddb0907022555ab7c5
