name: reuse
on:
  push:
    branches: [main]
  pull_request:
permissions: {}
jobs:
  reuse:
    name: reuse
    permissions:
      contents: read
    uses: openbunny/.github/.github/workflows/reusable-reuse.yml@9b06a5769f9356c4a192dd824e9d11b38d4bd2ff
