name: zizmor
on:
  push:
    branches: [main]
  pull_request:
permissions: {}
jobs:
  zizmor:
    name: zizmor
    permissions:
      contents: read
    uses: openbunny/.github/.github/workflows/reusable-zizmor.yml@0ef30bf859265abac45761ddb0907022555ab7c5
