name: zizmor
on:
  push:
    branches: [main]
  pull_request:
permissions: {}
jobs:
  zizmor:
    name: zizmor
    permissions:
      contents: read
    uses: openbunny/.github/.github/workflows/reusable-zizmor.yml@2383033519e5dd89bfd4e832659933a145e7acde
